# Generated by Django 3.2.10 on 2021-12-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
