# Generated by Django 3.2.10 on 2021-12-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0002_alter_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrate',
            name='rates_number',
            field=models.IntegerField(default=0),
        ),
    ]
