# Generated by Django 3.2.10 on 2021-12-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0003_carrate_rates_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrate',
            name='rates_number',
        ),
        migrations.AddField(
            model_name='car',
            name='rates_number',
            field=models.IntegerField(default=0),
        ),
    ]
